kibana:
  image: docker.elastic.co/kibana/kibana:7.12.1
  container_name: kibana    
  environment:
    SERVER_NAME: "kibana"
    ELASTICSEARCH_HOSTS: http://172.17.0.3:9200
  ports:
      - 5601:5601
  volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml