FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install sudo


#sudo docker build -tag mijenkins .
#sudo docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home mijenkins